  
//
// Copyright 2004 P&P Software GmbH - All Rights Reserved
//
// DC_SampleMonitoringProfile.h
//
// This file was automatically generated by an XSL program

#ifndef DC_SampleMonitoringProfile_H
#define DC_SampleMonitoringProfile_H

#include "../GeneralInclude/ForwardDeclarations.h"
#include "../GeneralInclude/BasicTypes.h"
#include "../FDIR/MonitoringProfile.h"
#include "../Qom/object.h"

/**
 * Sample application-specific monitoring profile.
 * <p>
 * This is a stub class. It provides dummy implementations for some of the virtual
 * methods of its superclass. 
 * This class was automatically generated by an XSL program that processes the
 * XML-based <i>target application model</i>. The XSL program searches 
 * the  searches the application model for all "MonitoringProfile" elements
 * which have a "Custom" subelement that indicates that a custom recovery action
 * class must be created. For each such element a class header file is created.
 * The base class of the generated class is assumed to be the class in the
 * "type" attribute of the MonitoringProfile element. 
 * The information in the application model is used to decide which virtual methods
 * should be overridden.
 * @todo Modify the generator meta-component generateMonitoringProfile to generate the code
 * that sets the class identifier and to treat the default attributes in the custom monitoring profile description.
 * @author Automatically Generated Class
 * @version 1.0
 */


void DC_SampleMonitoringProfile_register(void);


/////////////////////////////////////////////////////////////////////////////////
//
//                              class and struct
//
/////////////////////////////////////////////////////////////////////////////////

struct DC_SampleMonitoringProfile {
    MonitoringProfile parent;
};


struct DC_SampleMonitoringProfileClass {
    MonitoringProfileClass parent_class;
    /**
     * This is a stub method that must be completed by the application developer.
     * This stub provides a default implementation that always returns false (no deviation from
     * profile).
     * @return always return false 
     */
    bool (*doProfileCheckFloat)(void *obj, TD_Float value);

    /**
     * This is a stub method that must be completed by the application developer.
     * This stub provides a default implementation that always returns false (no deviation from
     * profile).
     * @return always return false 
     */
    bool (*doProfileCheckInt)(void *obj, TD_Integer value);
};


#define DC_SAMPLEMONITORINGPROFILE_GET_CLASS(obj) \
         OBJECT_GET_CLASS(DC_SampleMonitoringProfileClass, obj, TYPE_DC_SAMPLEMONITORINGPROFILE)


#define DC_SAMPLEMONITORINGPROFILE_CLASS(klass) \
         OBJECT_CLASS_CHECK(DC_SampleMonitoringProfileClass, klass, TYPE_DC_SAMPLEMONITORINGPROFILE)


#define DC_SAMPLEMONITORINGPROFILE(obj) \
         OBJECT_CHECK(DC_SampleMonitoringProfile, obj, TYPE_DC_SAMPLEMONITORINGPROFILE)


DC_SampleMonitoringProfile* DC_SampleMonitoringProfile_new(void);


#endif
             