  
//
// Copyright 2004 P&P Software GmbH - All Rights Reserved
//
// DC_SampleMonitoringProfile.c
//
// This file was automatically generated by an XSL program

#include "../GeneralInclude/CompilerSwitches.h"
#include "../GeneralInclude/Constants.h"
#include "../FDIR/MonitoringProfile.h"
#include "../FDIR/DC_SampleMonitoringProfile.h"

/////////////////////////////////////////////////////////////////////////////////
//
//                    non-pure virtual  method(s) definition
//
/////////////////////////////////////////////////////////////////////////////////


static void doProfileCheckFloat(void *obj,TD_Float value)
{

      // insert application-specific code here
      return false;
}

static void doProfileCheckInt(void *obj,TD_Integer value)
{
      // insert application-specific code here
      return false;
}



///////////////////////////////////////////////////////////////////////////////
//
//                   object constructor and destructor
//
///////////////////////////////////////////////////////////////////////////////

// the following may be useful if you don't need it, just delete.
// DC_SampleMonitoringProfile *this = DC_SAMPLEMONITORINGPROFILE(obj)
static void instance_init(Object *obj)
{
      // insert application-specific code here
}

DC_SampleMonitoringProfile* DC_SampleMonitoringProfile_new(void)
{
        return (DC_SampleMonitoringProfile*)object_new(TYPE_DC_SAMPLEMONITORINGPROFILE);

}



///////////////////////////////////////////////////////////////////////////////
//
//                   binding and type registration
//
///////////////////////////////////////////////////////////////////////////////

static void class_init(ObjectClass *oc, void *data)
{
DC_SampleMonitoringProfileClass *dc_p_class = DC_SAMPLEMONITORINGPROFILE_CLASS(oc);

        dc_p_class->doProfileCheckFloat = doProfileCheckFloat;
        dc_p_class->doProfileCheckInt = doProfileCheckInt;

}

static const TypeInfo type_info = {
        .name = TYPE_DC_SAMPLEMONITORINGPROFILE,
        .parent = TYPE_MONITORINGPROFILE,
        .instance_size = sizeof(DC_SampleMonitoringProfile),
        .abstract = false,
        .class_size = sizeof(DC_SampleMonitoringProfileClass),
        .instance_init = instance_init,
        .class_init = class_init,

};

void DC_SampleMonitoringProfile_register(void)
{
        type_register_static(&type_info);

}

            