#ifndef EVENT_TYPE_H_
#define EVENT_TYPE_H_

#define EVT_RT_RECV_DATA 10
#define EVT_RT_RECV_DATA_ERR 20
#define EVT_1553_RECV_COMMAND 30
#define EVT_1553_RECV_COMMAND_ERR 40
#define EVT_1553_RETURN_DATA 50
#define EVT_1553_RETURN_DATA_ERR 60
#define EVT_WRITE_OVERFLOW 70
#define EVT_WAIT_OVER_TIME 80
#define EVT_RED_LIGHT_READ_ERR 90
#define EVT_APP_READ_BLOCK_OVERFLOW 100
#define EVT_APP_WRITE_ERR 101
#define EVT_APP_WRITE_BLOCK_OVERFLOW 110
#define EVT_RT_SECTION_WRITE_ERR 120
#define EVT_COMMAND_OVER_TIME 130
#define EVT_APP_DATA_SIZE_ERR 140
#define EVT_COUNT_ERR 150
#endif
