  
//
// Copyright 2004 P&P Software GmbH - All Rights Reserved
//
// DC_SBY_PostSepFsmState.c
//
// This file was automatically generated by an XSL program

#include "../GeneralInclude/CompilerSwitches.h"
#include "../GeneralInclude/Constants.h"
#include "../FSM/FsmState.h"
#include "../FSM/DC_SBY_PostSepFsmState.h"

/////////////////////////////////////////////////////////////////////////////////
//
//                    non-pure virtual  method(s) definition
//
/////////////////////////////////////////////////////////////////////////////////


    
static void doInit(void *obj) {
      return FSMSTATE_GET_CLASS(obj)->doInit((void*)(obj));
      // remove previous statement and insert application-specific code here
}
    
static void doContinue(void *obj) {
      return;
}
          
static void doExit(void *obj) {
      return FSMSTATE_GET_CLASS(obj)->doExit((void*)(obj));
      // remove previous statement and insert application-specific code here
}
    
static bool isFinished(void *obj) {
      return DC_SBY_POSTSEPFSMSTATE_GET_CLASS(obj)->isFinished((void*)(obj));
      // remove previous statement and insert application-specific code here
}
    


///////////////////////////////////////////////////////////////////////////////
//
//                   object constructor and destructor
//
///////////////////////////////////////////////////////////////////////////////

// the following may be useful if you don't need it, just delete.
// DC_SBY_PostSepFsmState *this = DC_SBY_POSTSEPFSMSTATE(obj)
static void instance_init(Object *obj)
{
      // insert application-specific code here
}

DC_SBY_PostSepFsmState* DC_SBY_PostSepFsmState_new(void)
{
        return (DC_SBY_PostSepFsmState*)object_new(TYPE_DC_SBY_POSTSEPFSMSTATE);

}



///////////////////////////////////////////////////////////////////////////////
//
//                   binding and type registration
//
///////////////////////////////////////////////////////////////////////////////

static void class_init(ObjectClass *oc, void *data)
{
DC_SBY_PostSepFsmStateClass *dc_p_class = DC_SBY_POSTSEPFSMSTATE_CLASS(oc);

    
        dc_p_class->doInit=doInit;
    
        dc_p_class->doContinue=doContinue;
          
        dc_p_class->doExit=doExit;
    
        dc_p_class->isFinished=isFinished;
    

}

static const TypeInfo type_info = {
        .name = TYPE_DC_SBY_POSTSEPFSMSTATE,
        .parent = TYPE_FSMSTATE,
        .instance_size = sizeof(DC_SBY_PostSepFsmState),
        .abstract = false,
        .class_size = sizeof(DC_SBY_PostSepFsmStateClass),
        .instance_init = instance_init,
        .class_init = class_init,

};

void DC_SBY_PostSepFsmState_register(void)
{
        type_register_static(&type_info);

}
            