  
//
// Copyright 2004 P&P Software GmbH - All Rights Reserved
//
// DC_AfsFsmState.c
//
// This file was automatically generated by an XSL program

#include "../GeneralInclude/CompilerSwitches.h"
#include "../GeneralInclude/Constants.h"
#include "../FSM/FsmState.h"
#include "../FSM/DC_AfsFsmState.h"

/////////////////////////////////////////////////////////////////////////////////
//
//                    non-pure virtual  method(s) definition
//
/////////////////////////////////////////////////////////////////////////////////


    
static void doInit(void *obj) {
      return FSMSTATE_GET_CLASS(obj)->doInit((void*)(obj));
      // remove previous statement and insert application-specific code here
}
    
static void doContinue(void *obj) {
      return;
}
          
static void doExit(void *obj) {
      return FSMSTATE_GET_CLASS(obj)->doExit((void*)(obj));
      // remove previous statement and insert application-specific code here
}
    


///////////////////////////////////////////////////////////////////////////////
//
//                   object constructor and destructor
//
///////////////////////////////////////////////////////////////////////////////

// the following may be useful if you don't need it, just delete.
// DC_AfsFsmState *this = DC_AFSFSMSTATE(obj)
static void instance_init(Object *obj)
{
      // insert application-specific code here
}

DC_AfsFsmState* DC_AfsFsmState_new(void)
{
        return (DC_AfsFsmState*)object_new(TYPE_DC_AFSFSMSTATE);

}



///////////////////////////////////////////////////////////////////////////////
//
//                   binding and type registration
//
///////////////////////////////////////////////////////////////////////////////

static void class_init(ObjectClass *oc, void *data)
{
DC_AfsFsmStateClass *dc_p_class = DC_AFSFSMSTATE_CLASS(oc);

    
        dc_p_class->doInit=doInit;
    
        dc_p_class->doContinue=doContinue;
          
        dc_p_class->doExit=doExit;
    

}

static const TypeInfo type_info = {
        .name = TYPE_DC_AFSFSMSTATE,
        .parent = TYPE_FSMSTATE,
        .instance_size = sizeof(DC_AfsFsmState),
        .abstract = false,
        .class_size = sizeof(DC_AfsFsmStateClass),
        .instance_init = instance_init,
        .class_init = class_init,

};

void DC_AfsFsmState_register(void)
{
        type_register_static(&type_info);

}
            