  
//
// Copyright 2004 P&P Software GmbH - All Rights Reserved
//
// DC_SCM_FsmState.h
//
// This file was automatically generated by an XSL program

#ifndef DC_SCM_FsmState_H
#define DC_SCM_FsmState_H

#include "../GeneralInclude/ForwardDeclarations.h"
#include "../GeneralInclude/BasicTypes.h"
#include "../FSM/FsmState.h"
#include "../Qom/object.h"

/**
 * Sample FsmState application class. This FsmState models the SCM mode logic.
 * <p>
 * This is a stub class. It provides dummy implementations for some of the virtual
 * methods of its superclass. 
 * This class was automatically generated by an XSL program that processes the
 * XML-based <i>target application model</i>. The XSL program  
 * searches the application model for all "FsmState" elements
 * which have a "Custom" subelement that indicates that a custom FsmState
 * class must be created. For each such element a class header file is created.
 * The base class of the generated class is assumed to be the class in the
 * "type" attribute of the FsmState element. 
 * The information in the application model is used to decide which virtual methods
 * should be overridden.
 * @todo Modify the generator meta-component generateRecoveryAction to generate the code
 * that sets the class identifier and to treat the default attributes in the custom recovery action description.
 * @author Automatically Generated Class
 * @version 1.0
 */

void DC_SCM_FsmState_register(void);


/////////////////////////////////////////////////////////////////////////////////
//
//                              class and struct
//
/////////////////////////////////////////////////////////////////////////////////

struct DC_SCM_FsmState {
    FsmState parent;
};


struct DC_SCM_FsmStateClass {
    FsmStateClass parent_class;
    
    /**
     * Initialization action for the sample FsmState application class.
     * <p>
     * This is a stub method that must be completed by the application developer.
     * This stub provides a default implementation that calls the <code>doInit</code> 
     * method of the superclass.
     */
    void (*doInit)(void *obj);
    
    /**
     * Activate the SCM_FSM state machine.
     * <p>
     * This is a stub method that must be completed by the application developer.
     * This stub provides a default implementation that returns without taking any action.
     */
    void (*doContinue)(void *obj);
          
    /**
     * Termination action for the sample FsmState application class.
     * <p>
     * This is a stub method that must be completed by the application developer.
     * This stub provides a default implementation that calls the <code>isFinished</code> 
     * method of the superclass.
     * @return true if the continuation action of this state has terminated, false otherwise
     */
    bool (*isFinished)(void *obj);
    
};


#define DC_SCM_FSMSTATE_GET_CLASS(obj) \
             OBJECT_GET_CLASS(DC_SCM_FsmStateClass, obj, TYPE_DC_SCM_FSMSTATE)


#define DC_SCM_FSMSTATE_CLASS(klass) \
             OBJECT_CLASS_CHECK(DC_SCM_FsmStateClass, klass, TYPE_DC_SCM_FSMSTATE)


#define DC_SCM_FSMSTATE(obj) \
             OBJECT_CHECK(DC_SCM_FsmState, obj, TYPE_DC_SCM_FSMSTATE)


DC_SCM_FsmState* DC_SCM_FsmState_new(void);



#endif
             