  
//
// Copyright 2004 P&P Software GmbH - All Rights Reserved
//
// DC_SampleControlBlock_2.c
//
// This file was automatically generated by an XSL program

#include "../GeneralInclude/CompilerSwitches.h"
#include "../GeneralInclude/Constants.h"  
#include "../Data/DataPool.h" 
#include "../Data/DataPoolControlBlock.h"
#include "../Data/DC_SampleControlBlock_2.h"




/////////////////////////////////////////////////////////////////////////////////
//
//                    non-pure virtual  method(s) definition
//
/////////////////////////////////////////////////////////////////////////////////


static void propagateState(void *obj){
       return;
       // remove previous statement and insert application-specific code here
}


static void updateOutput(void *obj)
{

       return;
       // remove previous statements and insert application-specific code here

}

static void reset(void *obj)
{
        return;
        // remove previous statement and insert application-specific code here

}



///////////////////////////////////////////////////////////////////////////////
//
//                   object constructor and destructor
//
///////////////////////////////////////////////////////////////////////////////

// the following may be useful if you don't need it, just delete.
// DC_SampleControlBlock_2 *This = DC_SAMPLECONTROLBLOCK_2(obj)
static void instance_init(Object *obj)
{

        DATAPOOLCONTROLBLOCK_GET_CLASS(obj)->setNumberOfInputs(obj, 1);
        DATAPOOLCONTROLBLOCK_GET_CLASS(obj)->setNumberOfOutputs(obj, 1);
        DATAPOOLCONTROLBLOCK_GET_CLASS(obj)->setNumberOfParameters(obj, 1);
        DATAPOOLCONTROLBLOCK_GET_CLASS(obj)->setNumberOfStates(obj, 0);
        // Update the number of states (if necessary) and insert any other application-specific code here
}

DC_SampleControlBlock_2* DC_SampleControlBlock_2_new(void)
{
        return (DC_SampleControlBlock_2*)object_new(TYPE_DC_SAMPLECONTROLBLOCK_2);

}



///////////////////////////////////////////////////////////////////////////////
//
//                   binding and type registration
//
///////////////////////////////////////////////////////////////////////////////

static void class_init(ObjectClass *oc, void *data)
{
        DC_SampleControlBlock_2Class *dc_p_class = DC_SAMPLECONTROLBLOCK_2_CLASS(oc);

        dc_p_class->propagateState = propagateState;
        dc_p_class->updateOutput = updateOutput;
        dc_p_class->reset = reset;

}

static const TypeInfo type_info = {
        .name = TYPE_DC_SAMPLECONTROLBLOCK_2,
        .parent = TYPE_DATAPOOLCONTROLBLOCK,
        .instance_size = sizeof(DC_SampleControlBlock_2),
        .abstract = false,
        .class_size = sizeof(DC_SampleControlBlock_2Class),
        .instance_init = instance_init,
        .class_init = class_init,

};

void DC_SampleControlBlock_2_register(void)
{
        type_register_static(&type_info);
}
        