  
//
// Copyright 2003 P&P Software GmbH - All Rights Reserved
//
// DC_SampleR2Database.c
//
// This file was automatically generated by an XSL program
//

#include "../GeneralInclude/CompilerSwitches.h"
#include "../GeneralInclude/DebugSupport.h"
#include "../GeneralInclude/BasicTypes.h"
#include "../GeneralInclude/ClassId.h"
#include "../GeneralInclude/Constants.h"
#include "../Base/CC_RootObject.h"
#include "DC_SampleR2Database.h"

static unsigned int const CharCode = 1;
static unsigned int const UnsignedCharCode = 2;
static unsigned int const ShortCode = 3;
static unsigned int const UnsignedShortCode = 4;
static unsigned int const IntCode = 5;
static unsigned int const UnsignedIntCode = 6;
static unsigned int const BoolCode = 7;
static unsigned int const FloatCode = 8;
static unsigned int const DoubleCode = 9;



///////////////////////////////////////////////////////////////////////////////
//
//                  non-virtual member method(s) definition
//
///////////////////////////////////////////////////////////////////////////////



void DC_SampleR2Database_setDefaultTable(DC_SampleR2Database *this, char* pDefTable){
   assert( pDefTable != pNULL );
   this->pDefaultTable = pDefTable;
}

void DC_SampleR2Database_setOperationalTable(DC_SampleR2Database *this, char* pOperTable){
   assert( pOperTable != pNULL );
   this->pOperationalTable = pOperTable;
}





///////////////////////////////////////////////////////////////////////////////
//
//                    non-pure virtual  method(s) definition
//
///////////////////////////////////////////////////////////////////////////////



static void reset(void *obj)
{
assert( DC_SAMPLER2DATABASE(obj)->pDefaultTable != pNULL ) ;
assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( DC_SAMPLER2DATABASE(obj)->tableLength > 0 );
   for (TD_DatabaseId i=0; i<DC_SAMPLER2DATABASE(obj)->tableLength; i++)
      DC_SAMPLER2DATABASE(obj)->pOperationalTable[i] = DC_SAMPLER2DATABASE(obj)->pDefaultTable[i];
   DC_SAMPLER2DATABASE(obj)->resetWasCalled = true;


DC_SAMPLER2DATABASE(obj)->pPar[1] = DC_SAMPLER2DATABASE(obj)->pOperationalTable+0;DC_SAMPLER2DATABASE(obj)->parType[1] = FloatCode;DC_SAMPLER2DATABASE(obj)->pPar[2] = DC_SAMPLER2DATABASE(obj)->pOperationalTable+8;DC_SAMPLER2DATABASE(obj)->parType[2] = FloatCode;DC_SAMPLER2DATABASE(obj)->pPar[3] = DC_SAMPLER2DATABASE(obj)->pOperationalTable+16;DC_SAMPLER2DATABASE(obj)->parType[3] = FloatCode;DC_SAMPLER2DATABASE(obj)->pPar[4] = DC_SAMPLER2DATABASE(obj)->pOperationalTable+24;DC_SAMPLER2DATABASE(obj)->parType[4] = FloatCode;
}


static void setParameterInt(void obj*, TD_DatabaseId parId, int newValue) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==IntCode) );
   
   if (parId > DC_SAMPLER2DATABASE(obj)->maxParId) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return;
   }
   if (DC_SAMPLER2DATABASE(obj)->parType[parId]!=IntCode) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return;
   }
   
   *( (int*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]) ) = newValue;
}

static void setParameterUnsignedInt(void obj*, TD_DatabaseId parId, unsigned int newValue) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==UnsignedIntCode) );
   
   if (parId > DC_SAMPLER2DATABASE(obj)->maxParId) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return;
   }
   if (DC_SAMPLER2DATABASE(obj)->parType[parId]!=UnsignedIntCode) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return;
   }
   
   *( (unsigned int*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]) ) = newValue;
}

static void setParameterShort(void obj*, TD_DatabaseId parId, short newValue) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==ShortCode) );
   
   if (parId > DC_SAMPLER2DATABASE(obj)->maxParId) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return;
   }
   if (DC_SAMPLER2DATABASE(obj)->parType[parId]!=ShortCode) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return;
   }
   
   *( (short*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]) ) = newValue;
}

static void setParameterUnsignedShort(void obj*, TD_DatabaseId parId, unsigned short newValue) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==UnsignedShortCode) );
   
   if (parId > DC_SAMPLER2DATABASE(obj)->maxParId) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return;
   }
   if (DC_SAMPLER2DATABASE(obj)->parType[parId]!=UnsignedShortCode) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return;
   }
   
   *( (unsigned short*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]) ) = newValue;
}

static void setParameterChar(void obj*, TD_DatabaseId parId, char newValue) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==CharCode) );
   
   if (parId > DC_SAMPLER2DATABASE(obj)->maxParId) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return;
   }
   if (DC_SAMPLER2DATABASE(obj)->parType[parId]!=CharCode) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return;
   }
   
   *( (char*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]) ) = newValue;
}

static void setParameterUnsignedChar(void obj*, TD_DatabaseId parId, unsigned char newValue) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==UnsignedCharCode) );
   
   if (parId > DC_SAMPLER2DATABASE(obj)->maxParId) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return;
   }
   if (DC_SAMPLER2DATABASE(obj)->parType[parId]!=UnsignedCharCode) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return;
   }
   
   *( (unsigned char*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]) ) = newValue;
}

static void setParameterBool(void obj*, TD_DatabaseId parId, bool newValue) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==BoolCode) );
   
   if (parId > DC_SAMPLER2DATABASE(obj)->maxParId) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return;
   }
   if (DC_SAMPLER2DATABASE(obj)->parType[parId]!=BoolCode) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return;
   }
   
   *( (bool*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]) ) = newValue;
}

static void setParameterFloat(void obj*, TD_DatabaseId parId, float newValue) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==FloatCode) );
   
   if (parId > DC_SAMPLER2DATABASE(obj)->maxParId) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return;
   }
   if (DC_SAMPLER2DATABASE(obj)->parType[parId]!=FloatCode) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return;
   }
   
   *( (float*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]) ) = newValue;
}

static void setParameterDouble(void obj*, TD_DatabaseId parId, double newValue) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==DoubleCode) );
   
   if (parId > DC_SAMPLER2DATABASE(obj)->maxParId) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return;
   }
   if (DC_SAMPLER2DATABASE(obj)->parType[parId]!=DoubleCode) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return;
   }
   
   *( (double*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]) ) = newValue;
}

static int* getParameterInt(void *obj, TD_DatabaseId parId) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==IntCode) );
   
   return *(int*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]);
}

static unsigned int* getParameterUnsignedInt(void *obj, TD_DatabaseId parId) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==UnsignedIntCode) );
   
   return *(unsigned int*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]);
}

static short* getParameterShort(void *obj, TD_DatabaseId parId) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==ShortCode) );
   
   return *(short*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]);
}

static unsigned short* getParameterUnsignedShort(void *obj, TD_DatabaseId parId) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==UnsignedShortCode) );
   
   return *(unsigned short*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]);
}

static char* getParameterChar(void *obj, TD_DatabaseId parId) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==CharCode) );
   
   return *(char*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]);
}

static unsigned char* getParameterUnsignedChar(void *obj, TD_DatabaseId parId) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==UnsignedCharCode) );
   
   return *(unsigned char*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]);
}

static bool* getParameterBool(void *obj, TD_DatabaseId parId) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==BoolCode) );
   
   return *(bool*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]);
}

static float* getParameterFloat(void *obj, TD_DatabaseId parId) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==FloatCode) );
   
   return *(float*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]);
}

static double* getParameterDouble(void *obj, TD_DatabaseId parId) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==DoubleCode) );
   
   return *(double*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]);
}

static int* getParameterPointerInt(void *obj, TD_DatabaseId parId) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==IntCode) );
   
   if (parId > DC_SAMPLER2DATABASE(obj)->maxParId) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return pNULL;
   }
   if (DC_SAMPLER2DATABASE(obj)->parType[parId]!=IntCode) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return pNULL;
   }
   
   return (int*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]);
}

static unsigned int* getParameterPointerUnsignedInt(void *obj, TD_DatabaseId parId) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==UnsignedIntCode) );
   
   if (parId > DC_SAMPLER2DATABASE(obj)->maxParId) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return pNULL;
   }
   if (DC_SAMPLER2DATABASE(obj)->parType[parId]!=UnsignedIntCode) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return pNULL;
   }
   
   return (unsigned int*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]);
}

static short* getParameterPointerShort(void *obj, TD_DatabaseId parId) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==ShortCode) );
   
   if (parId > DC_SAMPLER2DATABASE(obj)->maxParId) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return pNULL;
   }
   if (DC_SAMPLER2DATABASE(obj)->parType[parId]!=ShortCode) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return pNULL;
   }
   
   return (short*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]);
}

static unsigned short* getParameterPointerUnsignedShort(void *obj, TD_DatabaseId parId) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==UnsignedShortCode) );
   
   if (parId > DC_SAMPLER2DATABASE(obj)->maxParId) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return pNULL;
   }
   if (DC_SAMPLER2DATABASE(obj)->parType[parId]!=UnsignedShortCode) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return pNULL;
   }
   
   return (unsigned short*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]);
}

static char* getParameterPointerChar(void *obj, TD_DatabaseId parId) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==CharCode) );
   
   if (parId > DC_SAMPLER2DATABASE(obj)->maxParId) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return pNULL;
   }
   if (DC_SAMPLER2DATABASE(obj)->parType[parId]!=CharCode) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return pNULL;
   }
   
   return (char*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]);
}

static unsigned char* getParameterPointerUnsignedChar(void *obj, TD_DatabaseId parId) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==UnsignedCharCode) );
   
   if (parId > DC_SAMPLER2DATABASE(obj)->maxParId) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return pNULL;
   }
   if (DC_SAMPLER2DATABASE(obj)->parType[parId]!=UnsignedCharCode) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return pNULL;
   }
   
   return (unsigned char*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]);
}

static bool* getParameterPointerBool(void *obj, TD_DatabaseId parId) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==BoolCode) );
   
   if (parId > DC_SAMPLER2DATABASE(obj)->maxParId) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return pNULL;
   }
   if (DC_SAMPLER2DATABASE(obj)->parType[parId]!=BoolCode) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return pNULL;
   }
   
   return (bool*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]);
}

static float* getParameterPointerFloat(void *obj, TD_DatabaseId parId) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==FloatCode) );
   
   if (parId > DC_SAMPLER2DATABASE(obj)->maxParId) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return pNULL;
   }
   if (DC_SAMPLER2DATABASE(obj)->parType[parId]!=FloatCode) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return pNULL;
   }
   
   return (float*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]);
}

static double* getParameterPointerDouble(void *obj, TD_DatabaseId parId) {
   assert( DC_SAMPLER2DATABASE(obj)->pOperationalTable != pNULL );
   assert( (parId <= DC_SAMPLER2DATABASE(obj)->maxParId) && (DC_SAMPLER2DATABASE(obj)->parType[parId]==DoubleCode) );
   
   if (parId > DC_SAMPLER2DATABASE(obj)->maxParId) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return pNULL;
   }
   if (DC_SAMPLER2DATABASE(obj)->parType[parId]!=DoubleCode) {
       DC_EventRepository* dc_e_r=CC_RootObject_getEventRepository();
      DC_EVENTREPOSITORY_GET_CLASS(dc_e_r)->create(obj,EVT_ILLEGAL_DB_ACCESS);
       return pNULL;
   }
   
   return (double*)(DC_SAMPLER2DATABASE(obj)->pPar[parId]);
}



///////////////////////////////////////////////////////////////////////////////
//
//                   object constructor and destructor
//
///////////////////////////////////////////////////////////////////////////////

// the following may be useful if you don't need it, just delete.
// DC_SampleR2Database *this = DC_SAMPLER2DATABASE(obj)
static void instance_init(Object *obj)
{
   (obj)->setClassId(ID_SAMPLER2DATABASE);
   DC_SAMPLER2DATABASE(obj)->pDefaultTable = pNULL;
   DC_SAMPLER2DATABASE(obj)->pOperationalTable = pNULL;
   DC_SAMPLER2DATABASE(obj)->resetWasCalled = false;

   DC_SAMPLER2DATABASE(obj)->maxParId = 4;
   DC_SAMPLER2DATABASE(obj)->pPar = (char*)malloc(maxParId+1);
   DC_SAMPLER2DATABASE(obj)->parType = (char*)malloc(maxParId+1);
   for (TD_DatabaseId i=0; i<DC_SAMPLER2DATABASE(obj)->maxParId; i++)  {
       DC_SAMPLER2DATABASE(obj)->pPar[i] = pNULL;
       DC_SAMPLER2DATABASE(obj)->parType[i] = -1;
   }

}
DC_SampleR2Database *DC_SampleR2Database_new(void)
{
    return (DC_SampleR2Database*)object_new(TYPE_DC_SAMPLER2DATABASE);
}



///////////////////////////////////////////////////////////////////////////////
//
//                   binding and type registration
//
///////////////////////////////////////////////////////////////////////////////

static void class_init(ObjectClass *oc, void *data)
{
    DC_SampleR2DatabaseClass *dc_sr2dc = DC_SAMPLER2DATABASE_CLASS(oc);

    dc_sr2dc->reset = reset;
    dc_sr2dc->setParameterInt = setParameterInt;
    dc_sr2dc->setParameterUnsignedInt = setParameterUnsignedInt;
    dc_sr2dc->setParameterShort = setParameterShort;
    dc_sr2dc->setParameterUnsignedShort = setParameterUnsignedShort;
    dc_sr2dc->setParameterChar = setParameterChar;
    dc_sr2dc->setParameterUnsignedChar = setParameterUnsignedChar;
    dc_sr2dc->setParameterBool = setParameterBool;
    dc_sr2dc->setParameterFloat = setParameterFloat;
    dc_sr2dc->setParameterDouble = setParameterDouble;
    dc_sr2dc->getParameterInt = getParameterInt;
    dc_sr2dc->getParameterUnsignedInt = getParameterUnsignedInt;
    dc_sr2dc->getParameterShort = getParameterShort;
    dc_sr2dc->getParameterUnsignedShort = getParameterUnsignedShort;
    dc_sr2dc->getParameterChar = getParameterChar;
    dc_sr2dc->getParameterUnsignedChar = getParameterUnsignedChar;
    dc_sr2dc->getParameterBool = getParameterBool;
    dc_sr2dc->getParameterFloat = getParameterFloat;
    dc_sr2dc->getParameterDouble = getParameterDouble;
    dc_sr2dc->getParameterPointerInt = getParameterPointerInt;
    dc_sr2dc->getParameterPointerUnsignedInt = getParameterPointerUnsignedInt;
    dc_sr2dc->getParameterPointerShort = getParameterPointerShort;
    dc_sr2dc->getParameterPointerUnsignedShort = getParameterPointerUnsignedShort;
    dc_sr2dc->getParameterPointerChar = getParameterPointerChar;
    dc_sr2dc->getParameterPointerUnsignedChar = getParameterPointerUnsignedChar;
    dc_sr2dc->getParameterPointerBool = getParameterPointerBool;
    dc_sr2dc->getParameterPointerFloat = getParameterPointerFloat;
    dc_sr2dc->getParameterPointerDouble = getParameterPointerDouble;
    dc_sr2dc->isObjectConfigured = isObjectConfigured;
    
}

static const TypeInfo type_info = {
    .name = TYPE_DC_SAMPLER2DATABASE,   
    .parent = TYPE_PARAMETERDATABASE,
    .instance_size = sizeof(DC_SampleR2Database),
    .abstract = false,
    .class_size = sizeof(DC_SampleR2DatabaseClass),
    .instance_init = instance_init,
    .class_init = class_init,
};

void DC_SampleR2Database_register(void)
{
    type_register_static(&type_info);
}

