
//
// Copyright 2003 P&P Software GmbH - All Rights Reserved
//
// CC_TelecommandFactory.c
//
// This file was automatically generated by an XSL program
//

#include "../GeneralInclude/CompilerSwitches.h"
#include "../GeneralInclude/DebugSupport.h"
#include "../GeneralInclude/BasicTypes.h"
#include "../GeneralInclude/ClassId.h"
#include "../GeneralInclude/Constants.h"  
#include "../Telecommand/DC_DummyPUSTelecommand.h"  
#include "../Telecommand/DC_DummyTelecommand.h"  
#include "../Telecommand/DC_PUSControlDataReporting.h"  
#include "../Telecommand/DC_PUSDefineDataReporting.h"  
#include "../Telecommand/DC_PUSDumpMemoryAbsolute.h"  
#include "../Telecommand/DC_PUSDumpMemoryOffset.h"  
#include "../Telecommand/DC_PUSMemoryLoadAbsolute.h"  
#include "../Telecommand/DC_PUSMemoryLoadOffset.h"  
#include "../Telecommand/DC_TestPUSTelecommand.h"  
#include "../Base/CC_RootObject.h"
#include "CC_TelecommandFactory.h"


///////////////////////////////////////////////////////////////////////////////
//
//                            class data
//
///////////////////////////////////////////////////////////////////////////////


static CC_TelecommandFactory* pInstance=pNULL;     


///////////////////////////////////////////////////////////////////////////////
//
//                            class  method(s) definition
//
///////////////////////////////////////////////////////////////////////////////


CC_TelecommandFactory* CC_TelecommandFactory_getInstance(void) {
    if (pInstance==pNULL)
        pInstance = CC_TelecommandFactory_new();
    return pInstance;
}

///////////////////////////////////////////////////////////////////////////////
//
//                  non-virtual member method(s) definition
//
///////////////////////////////////////////////////////////////////////////////


  
void CC_TelecommandFactory_setTelecommand(CC_TelecommandFactory *this,unsigned int i, DC_DummyPUSTelecommand* pItem) {
    assert(i<this->sizeDummyPUSTelecommand);
    assert(pItem!=pNULL);
    
    this->poolDummyPUSTelecommand[i] = pItem;
    DC_DUMMYPUSTELECOMMAND_GET_CLASS(this->poolDummyPUSTelecommand[i])->setInUse(false);
}

unsigned int CC_TelecommandFactory_getNumberDummyPUSTelecommand(CC_TelecommandFactory *this) {
    unsigned int counter = 0;
    for (unsigned int i=0; i<sizeDummyPUSTelecommand; i++)
        if ( DC_DUMMYPUSTELECOMMAND_GET_CLASS(this->poolDummyPUSTelecommand[i])->isInUse() )
            counter++;
    return counter;
}

unsigned int CC_TelecommandFactory_getCapacityDummyPUSTelecommand(CC_TelecommandFactory *this) {
    return this->sizeDummyPUSTelecommand;
}
DC_DummyPUSTelecommand* CC_TelecommandFactory_allocateDummyPUSTelecommand(CC_TelecommandFactory *this, ) {
    assert( this->isObjectConfigured() );
    for (unsigned int i=0; i<this->sizeDummyPUSTelecommand; i++)
    if (!DC_DUMMYPUSTELECOMMAND_GET_CLASS(this->poolDummyPUSTelecommand[i])->isInUse() ) { //这里C_GenerateDynamicFactoryBody.xsl是不是存在问题
        DC_DUMMYPUSTELECOMMAND_GET_CLASS(this->poolDummyPUSTelecommand[i])->setInUse(true);
           return this->poolDummyPUSTelecommand[i];
        }
    return pNULL;
}

bool CC_TelecommandFactory_isFreeDummyPUSTelecommand( *this, ) {
    for (unsigned int i=0; i<sizeDummyPUSTelecommand; i++)
        if ( !DC_DUMMYPUSTELECOMMAND_GET_CLASS(this->poolDummyPUSTelecommand[i])->isInUse() )
           return true;

    return false;
}

            
void CC_TelecommandFactory_setTelecommand(CC_TelecommandFactory *this,unsigned int i, DC_DummyTelecommand* pItem) {
    assert(i<this->sizeDummyTelecommand);
    assert(pItem!=pNULL);
    
    this->poolDummyTelecommand[i] = pItem;
    DC_DUMMYTELECOMMAND_GET_CLASS(this->poolDummyTelecommand[i])->setInUse(false);
}

unsigned int CC_TelecommandFactory_getNumberDummyTelecommand(CC_TelecommandFactory *this) {
    unsigned int counter = 0;
    for (unsigned int i=0; i<sizeDummyTelecommand; i++)
        if ( DC_DUMMYTELECOMMAND_GET_CLASS(this->poolDummyTelecommand[i])->isInUse() )
            counter++;
    return counter;
}

unsigned int CC_TelecommandFactory_getCapacityDummyTelecommand(CC_TelecommandFactory *this) {
    return this->sizeDummyTelecommand;
}
DC_DummyTelecommand* CC_TelecommandFactory_allocateDummyTelecommand(CC_TelecommandFactory *this, ) {
    assert( this->isObjectConfigured() );
    for (unsigned int i=0; i<this->sizeDummyTelecommand; i++)
    if (!DC_DUMMYTELECOMMAND_GET_CLASS(this->poolDummyTelecommand[i])->isInUse() ) { //这里C_GenerateDynamicFactoryBody.xsl是不是存在问题
        DC_DUMMYTELECOMMAND_GET_CLASS(this->poolDummyTelecommand[i])->setInUse(true);
           return this->poolDummyTelecommand[i];
        }
    return pNULL;
}

bool CC_TelecommandFactory_isFreeDummyTelecommand( *this, ) {
    for (unsigned int i=0; i<sizeDummyTelecommand; i++)
        if ( !DC_DUMMYTELECOMMAND_GET_CLASS(this->poolDummyTelecommand[i])->isInUse() )
           return true;

    return false;
}

            
void CC_TelecommandFactory_setTelecommand(CC_TelecommandFactory *this,unsigned int i, DC_PUSControlDataReporting* pItem) {
    assert(i<this->sizePUSControlDataReporting);
    assert(pItem!=pNULL);
    
    this->poolPUSControlDataReporting[i] = pItem;
    DC_PUSCONTROLDATAREPORTING_GET_CLASS(this->poolPUSControlDataReporting[i])->setInUse(false);
}

unsigned int CC_TelecommandFactory_getNumberPUSControlDataReporting(CC_TelecommandFactory *this) {
    unsigned int counter = 0;
    for (unsigned int i=0; i<sizePUSControlDataReporting; i++)
        if ( DC_PUSCONTROLDATAREPORTING_GET_CLASS(this->poolPUSControlDataReporting[i])->isInUse() )
            counter++;
    return counter;
}

unsigned int CC_TelecommandFactory_getCapacityPUSControlDataReporting(CC_TelecommandFactory *this) {
    return this->sizePUSControlDataReporting;
}
DC_PUSControlDataReporting* CC_TelecommandFactory_allocatePUSControlDataReporting(CC_TelecommandFactory *this, unsigned int MaxNumberSID) {
    assert( this->isObjectConfigured() );
    for (unsigned int i=0; i<this->sizePUSControlDataReporting; i++)
    if (DC_PUSCONTROLDATAREPORTING_GET_CLASS((this->poolPUSControlDataReporting[i]))->getMaxNumberSID()>=MaxNumberSID &&
    !DC_PUSCONTROLDATAREPORTING_GET_CLASS(this->poolPUSControlDataReporting[i])->isInUse() ) { //这里C_GenerateDynamicFactoryBody.xsl是不是存在问题
        DC_PUSCONTROLDATAREPORTING_GET_CLASS(this->poolPUSControlDataReporting[i])->setInUse(true);
           return this->poolPUSControlDataReporting[i];
        }
    return pNULL;
}

bool CC_TelecommandFactory_isFreePUSControlDataReporting( *this, unsigned int MaxNumberSID) {
    for (unsigned int i=0; i<sizePUSControlDataReporting; i++)
        if ( DC_PUSCONTROLDATAREPORTING_GET_CLASS(this->poolPUSControlDataReporting[i])->getMaxNumberSID()>=MaxNumberSID &&
             !DC_PUSCONTROLDATAREPORTING_GET_CLASS(this->poolPUSControlDataReporting[i])->isInUse() )
           return true;

    return false;
}

            
void CC_TelecommandFactory_setTelecommand(CC_TelecommandFactory *this,unsigned int i, DC_PUSDefineDataReporting* pItem) {
    assert(i<this->sizePUSDefineDataReporting);
    assert(pItem!=pNULL);
    
    this->poolPUSDefineDataReporting[i] = pItem;
    DC_PUSDEFINEDATAREPORTING_GET_CLASS(this->poolPUSDefineDataReporting[i])->setInUse(false);
}

unsigned int CC_TelecommandFactory_getNumberPUSDefineDataReporting(CC_TelecommandFactory *this) {
    unsigned int counter = 0;
    for (unsigned int i=0; i<sizePUSDefineDataReporting; i++)
        if ( DC_PUSDEFINEDATAREPORTING_GET_CLASS(this->poolPUSDefineDataReporting[i])->isInUse() )
            counter++;
    return counter;
}

unsigned int CC_TelecommandFactory_getCapacityPUSDefineDataReporting(CC_TelecommandFactory *this) {
    return this->sizePUSDefineDataReporting;
}
DC_PUSDefineDataReporting* CC_TelecommandFactory_allocatePUSDefineDataReporting(CC_TelecommandFactory *this, unsigned int NumberOfRawData) {
    assert( this->isObjectConfigured() );
    for (unsigned int i=0; i<this->sizePUSDefineDataReporting; i++)
    if (DC_PUSDEFINEDATAREPORTING_GET_CLASS((this->poolPUSDefineDataReporting[i]))->getNumberOfRawData()>=NumberOfRawData &&
    !DC_PUSDEFINEDATAREPORTING_GET_CLASS(this->poolPUSDefineDataReporting[i])->isInUse() ) { //这里C_GenerateDynamicFactoryBody.xsl是不是存在问题
        DC_PUSDEFINEDATAREPORTING_GET_CLASS(this->poolPUSDefineDataReporting[i])->setInUse(true);
           return this->poolPUSDefineDataReporting[i];
        }
    return pNULL;
}

bool CC_TelecommandFactory_isFreePUSDefineDataReporting( *this, unsigned int NumberOfRawData) {
    for (unsigned int i=0; i<sizePUSDefineDataReporting; i++)
        if ( DC_PUSDEFINEDATAREPORTING_GET_CLASS(this->poolPUSDefineDataReporting[i])->getNumberOfRawData()>=NumberOfRawData &&
             !DC_PUSDEFINEDATAREPORTING_GET_CLASS(this->poolPUSDefineDataReporting[i])->isInUse() )
           return true;

    return false;
}

            
void CC_TelecommandFactory_setTelecommand(CC_TelecommandFactory *this,unsigned int i, DC_PUSDumpMemoryAbsolute* pItem) {
    assert(i<this->sizePUSDumpMemoryAbsolute);
    assert(pItem!=pNULL);
    
    this->poolPUSDumpMemoryAbsolute[i] = pItem;
    DC_PUSDUMPMEMORYABSOLUTE_GET_CLASS(this->poolPUSDumpMemoryAbsolute[i])->setInUse(false);
}

unsigned int CC_TelecommandFactory_getNumberPUSDumpMemoryAbsolute(CC_TelecommandFactory *this) {
    unsigned int counter = 0;
    for (unsigned int i=0; i<sizePUSDumpMemoryAbsolute; i++)
        if ( DC_PUSDUMPMEMORYABSOLUTE_GET_CLASS(this->poolPUSDumpMemoryAbsolute[i])->isInUse() )
            counter++;
    return counter;
}

unsigned int CC_TelecommandFactory_getCapacityPUSDumpMemoryAbsolute(CC_TelecommandFactory *this) {
    return this->sizePUSDumpMemoryAbsolute;
}
DC_PUSDumpMemoryAbsolute* CC_TelecommandFactory_allocatePUSDumpMemoryAbsolute(CC_TelecommandFactory *this, unsigned int NumberOfRawData) {
    assert( this->isObjectConfigured() );
    for (unsigned int i=0; i<this->sizePUSDumpMemoryAbsolute; i++)
    if (DC_PUSDUMPMEMORYABSOLUTE_GET_CLASS((this->poolPUSDumpMemoryAbsolute[i]))->getNumberOfRawData()>=NumberOfRawData &&
    !DC_PUSDUMPMEMORYABSOLUTE_GET_CLASS(this->poolPUSDumpMemoryAbsolute[i])->isInUse() ) { //这里C_GenerateDynamicFactoryBody.xsl是不是存在问题
        DC_PUSDUMPMEMORYABSOLUTE_GET_CLASS(this->poolPUSDumpMemoryAbsolute[i])->setInUse(true);
           return this->poolPUSDumpMemoryAbsolute[i];
        }
    return pNULL;
}

bool CC_TelecommandFactory_isFreePUSDumpMemoryAbsolute( *this, unsigned int NumberOfRawData) {
    for (unsigned int i=0; i<sizePUSDumpMemoryAbsolute; i++)
        if ( DC_PUSDUMPMEMORYABSOLUTE_GET_CLASS(this->poolPUSDumpMemoryAbsolute[i])->getNumberOfRawData()>=NumberOfRawData &&
             !DC_PUSDUMPMEMORYABSOLUTE_GET_CLASS(this->poolPUSDumpMemoryAbsolute[i])->isInUse() )
           return true;

    return false;
}

            
void CC_TelecommandFactory_setTelecommand(CC_TelecommandFactory *this,unsigned int i, DC_PUSDumpMemoryOffset* pItem) {
    assert(i<this->sizePUSDumpMemoryOffset);
    assert(pItem!=pNULL);
    
    this->poolPUSDumpMemoryOffset[i] = pItem;
    DC_PUSDUMPMEMORYOFFSET_GET_CLASS(this->poolPUSDumpMemoryOffset[i])->setInUse(false);
}

unsigned int CC_TelecommandFactory_getNumberPUSDumpMemoryOffset(CC_TelecommandFactory *this) {
    unsigned int counter = 0;
    for (unsigned int i=0; i<sizePUSDumpMemoryOffset; i++)
        if ( DC_PUSDUMPMEMORYOFFSET_GET_CLASS(this->poolPUSDumpMemoryOffset[i])->isInUse() )
            counter++;
    return counter;
}

unsigned int CC_TelecommandFactory_getCapacityPUSDumpMemoryOffset(CC_TelecommandFactory *this) {
    return this->sizePUSDumpMemoryOffset;
}
DC_PUSDumpMemoryOffset* CC_TelecommandFactory_allocatePUSDumpMemoryOffset(CC_TelecommandFactory *this, unsigned int NumberOfRawData) {
    assert( this->isObjectConfigured() );
    for (unsigned int i=0; i<this->sizePUSDumpMemoryOffset; i++)
    if (DC_PUSDUMPMEMORYOFFSET_GET_CLASS((this->poolPUSDumpMemoryOffset[i]))->getNumberOfRawData()>=NumberOfRawData &&
    !DC_PUSDUMPMEMORYOFFSET_GET_CLASS(this->poolPUSDumpMemoryOffset[i])->isInUse() ) { //这里C_GenerateDynamicFactoryBody.xsl是不是存在问题
        DC_PUSDUMPMEMORYOFFSET_GET_CLASS(this->poolPUSDumpMemoryOffset[i])->setInUse(true);
           return this->poolPUSDumpMemoryOffset[i];
        }
    return pNULL;
}

bool CC_TelecommandFactory_isFreePUSDumpMemoryOffset( *this, unsigned int NumberOfRawData) {
    for (unsigned int i=0; i<sizePUSDumpMemoryOffset; i++)
        if ( DC_PUSDUMPMEMORYOFFSET_GET_CLASS(this->poolPUSDumpMemoryOffset[i])->getNumberOfRawData()>=NumberOfRawData &&
             !DC_PUSDUMPMEMORYOFFSET_GET_CLASS(this->poolPUSDumpMemoryOffset[i])->isInUse() )
           return true;

    return false;
}

            
void CC_TelecommandFactory_setTelecommand(CC_TelecommandFactory *this,unsigned int i, DC_PUSMemoryLoadAbsolute* pItem) {
    assert(i<this->sizePUSMemoryLoadAbsolute);
    assert(pItem!=pNULL);
    
    this->poolPUSMemoryLoadAbsolute[i] = pItem;
    DC_PUSMEMORYLOADABSOLUTE_GET_CLASS(this->poolPUSMemoryLoadAbsolute[i])->setInUse(false);
}

unsigned int CC_TelecommandFactory_getNumberPUSMemoryLoadAbsolute(CC_TelecommandFactory *this) {
    unsigned int counter = 0;
    for (unsigned int i=0; i<sizePUSMemoryLoadAbsolute; i++)
        if ( DC_PUSMEMORYLOADABSOLUTE_GET_CLASS(this->poolPUSMemoryLoadAbsolute[i])->isInUse() )
            counter++;
    return counter;
}

unsigned int CC_TelecommandFactory_getCapacityPUSMemoryLoadAbsolute(CC_TelecommandFactory *this) {
    return this->sizePUSMemoryLoadAbsolute;
}
DC_PUSMemoryLoadAbsolute* CC_TelecommandFactory_allocatePUSMemoryLoadAbsolute(CC_TelecommandFactory *this, unsigned int MaxNumberData, unsigned int MaxNumberBlocks) {
    assert( this->isObjectConfigured() );
    for (unsigned int i=0; i<this->sizePUSMemoryLoadAbsolute; i++)
    if (DC_PUSMEMORYLOADABSOLUTE_GET_CLASS((this->poolPUSMemoryLoadAbsolute[i]))->getMaxNumberData()>=MaxNumberData &&
    DC_PUSMEMORYLOADABSOLUTE_GET_CLASS((this->poolPUSMemoryLoadAbsolute[i]))->getMaxNumberBlocks()>=MaxNumberBlocks &&
    !DC_PUSMEMORYLOADABSOLUTE_GET_CLASS(this->poolPUSMemoryLoadAbsolute[i])->isInUse() ) { //这里C_GenerateDynamicFactoryBody.xsl是不是存在问题
        DC_PUSMEMORYLOADABSOLUTE_GET_CLASS(this->poolPUSMemoryLoadAbsolute[i])->setInUse(true);
           return this->poolPUSMemoryLoadAbsolute[i];
        }
    return pNULL;
}

bool CC_TelecommandFactory_isFreePUSMemoryLoadAbsolute( *this, unsigned int MaxNumberData, unsigned int MaxNumberBlocks) {
    for (unsigned int i=0; i<sizePUSMemoryLoadAbsolute; i++)
        if ( DC_PUSMEMORYLOADABSOLUTE_GET_CLASS(this->poolPUSMemoryLoadAbsolute[i])->getMaxNumberData()>=MaxNumberData &&
             DC_PUSMEMORYLOADABSOLUTE_GET_CLASS(this->poolPUSMemoryLoadAbsolute[i])->getMaxNumberBlocks()>=MaxNumberBlocks &&
             !DC_PUSMEMORYLOADABSOLUTE_GET_CLASS(this->poolPUSMemoryLoadAbsolute[i])->isInUse() )
           return true;

    return false;
}

            
void CC_TelecommandFactory_setTelecommand(CC_TelecommandFactory *this,unsigned int i, DC_PUSMemoryLoadOffset* pItem) {
    assert(i<this->sizePUSMemoryLoadOffset);
    assert(pItem!=pNULL);
    
    this->poolPUSMemoryLoadOffset[i] = pItem;
    DC_PUSMEMORYLOADOFFSET_GET_CLASS(this->poolPUSMemoryLoadOffset[i])->setInUse(false);
}

unsigned int CC_TelecommandFactory_getNumberPUSMemoryLoadOffset(CC_TelecommandFactory *this) {
    unsigned int counter = 0;
    for (unsigned int i=0; i<sizePUSMemoryLoadOffset; i++)
        if ( DC_PUSMEMORYLOADOFFSET_GET_CLASS(this->poolPUSMemoryLoadOffset[i])->isInUse() )
            counter++;
    return counter;
}

unsigned int CC_TelecommandFactory_getCapacityPUSMemoryLoadOffset(CC_TelecommandFactory *this) {
    return this->sizePUSMemoryLoadOffset;
}
DC_PUSMemoryLoadOffset* CC_TelecommandFactory_allocatePUSMemoryLoadOffset(CC_TelecommandFactory *this, unsigned int MaxNumberData, unsigned int MaxNumberBlocks) {
    assert( this->isObjectConfigured() );
    for (unsigned int i=0; i<this->sizePUSMemoryLoadOffset; i++)
    if (DC_PUSMEMORYLOADOFFSET_GET_CLASS((this->poolPUSMemoryLoadOffset[i]))->getMaxNumberData()>=MaxNumberData &&
    DC_PUSMEMORYLOADOFFSET_GET_CLASS((this->poolPUSMemoryLoadOffset[i]))->getMaxNumberBlocks()>=MaxNumberBlocks &&
    !DC_PUSMEMORYLOADOFFSET_GET_CLASS(this->poolPUSMemoryLoadOffset[i])->isInUse() ) { //这里C_GenerateDynamicFactoryBody.xsl是不是存在问题
        DC_PUSMEMORYLOADOFFSET_GET_CLASS(this->poolPUSMemoryLoadOffset[i])->setInUse(true);
           return this->poolPUSMemoryLoadOffset[i];
        }
    return pNULL;
}

bool CC_TelecommandFactory_isFreePUSMemoryLoadOffset( *this, unsigned int MaxNumberData, unsigned int MaxNumberBlocks) {
    for (unsigned int i=0; i<sizePUSMemoryLoadOffset; i++)
        if ( DC_PUSMEMORYLOADOFFSET_GET_CLASS(this->poolPUSMemoryLoadOffset[i])->getMaxNumberData()>=MaxNumberData &&
             DC_PUSMEMORYLOADOFFSET_GET_CLASS(this->poolPUSMemoryLoadOffset[i])->getMaxNumberBlocks()>=MaxNumberBlocks &&
             !DC_PUSMEMORYLOADOFFSET_GET_CLASS(this->poolPUSMemoryLoadOffset[i])->isInUse() )
           return true;

    return false;
}

            
void CC_TelecommandFactory_setTelecommand(CC_TelecommandFactory *this,unsigned int i, DC_TestPUSTelecommand* pItem) {
    assert(i<this->sizeTestPUSTelecommand);
    assert(pItem!=pNULL);
    
    this->poolTestPUSTelecommand[i] = pItem;
    DC_TESTPUSTELECOMMAND_GET_CLASS(this->poolTestPUSTelecommand[i])->setInUse(false);
}

unsigned int CC_TelecommandFactory_getNumberTestPUSTelecommand(CC_TelecommandFactory *this) {
    unsigned int counter = 0;
    for (unsigned int i=0; i<sizeTestPUSTelecommand; i++)
        if ( DC_TESTPUSTELECOMMAND_GET_CLASS(this->poolTestPUSTelecommand[i])->isInUse() )
            counter++;
    return counter;
}

unsigned int CC_TelecommandFactory_getCapacityTestPUSTelecommand(CC_TelecommandFactory *this) {
    return this->sizeTestPUSTelecommand;
}
DC_TestPUSTelecommand* CC_TelecommandFactory_allocateTestPUSTelecommand(CC_TelecommandFactory *this, ) {
    assert( this->isObjectConfigured() );
    for (unsigned int i=0; i<this->sizeTestPUSTelecommand; i++)
    if (!DC_TESTPUSTELECOMMAND_GET_CLASS(this->poolTestPUSTelecommand[i])->isInUse() ) { //这里C_GenerateDynamicFactoryBody.xsl是不是存在问题
        DC_TESTPUSTELECOMMAND_GET_CLASS(this->poolTestPUSTelecommand[i])->setInUse(true);
           return this->poolTestPUSTelecommand[i];
        }
    return pNULL;
}

bool CC_TelecommandFactory_isFreeTestPUSTelecommand( *this, ) {
    for (unsigned int i=0; i<sizeTestPUSTelecommand; i++)
        if ( !DC_TESTPUSTELECOMMAND_GET_CLASS(this->poolTestPUSTelecommand[i])->isInUse() )
           return true;

    return false;
}

            
/////////////////////////////////////////////////////////////////////////////////
//
//                    non-pure virtual  method(s) definition
//
/////////////////////////////////////////////////////////////////////////////////

static bool isObjectConfigured(void* obj) {

  if ( !CC_ROOTOBJECT(obj)->isObjectConfigured() )
        return false;
  
    if ( CC_TELECOMMANDFACTORY(obj)->poolDummyPUSTelecommand==pNULL )
        return false;

    for (unsigned int i=0; i< CC_TELECOMMANDFACTORY(obj)->sizeDummyPUSTelecommand; i++)
        if (  CC_TELECOMMANDFACTORY(obj)->poolDummyPUSTelecommand[i]==pNULL )
            return false;
     
    if ( CC_TELECOMMANDFACTORY(obj)->poolDummyTelecommand==pNULL )
        return false;

    for (unsigned int i=0; i< CC_TELECOMMANDFACTORY(obj)->sizeDummyTelecommand; i++)
        if (  CC_TELECOMMANDFACTORY(obj)->poolDummyTelecommand[i]==pNULL )
            return false;
     
    if ( CC_TELECOMMANDFACTORY(obj)->poolPUSControlDataReporting==pNULL )
        return false;

    for (unsigned int i=0; i< CC_TELECOMMANDFACTORY(obj)->sizePUSControlDataReporting; i++)
        if (  CC_TELECOMMANDFACTORY(obj)->poolPUSControlDataReporting[i]==pNULL )
            return false;
     
    if ( CC_TELECOMMANDFACTORY(obj)->poolPUSDefineDataReporting==pNULL )
        return false;

    for (unsigned int i=0; i< CC_TELECOMMANDFACTORY(obj)->sizePUSDefineDataReporting; i++)
        if (  CC_TELECOMMANDFACTORY(obj)->poolPUSDefineDataReporting[i]==pNULL )
            return false;
     
    if ( CC_TELECOMMANDFACTORY(obj)->poolPUSDumpMemoryAbsolute==pNULL )
        return false;

    for (unsigned int i=0; i< CC_TELECOMMANDFACTORY(obj)->sizePUSDumpMemoryAbsolute; i++)
        if (  CC_TELECOMMANDFACTORY(obj)->poolPUSDumpMemoryAbsolute[i]==pNULL )
            return false;
     
    if ( CC_TELECOMMANDFACTORY(obj)->poolPUSDumpMemoryOffset==pNULL )
        return false;

    for (unsigned int i=0; i< CC_TELECOMMANDFACTORY(obj)->sizePUSDumpMemoryOffset; i++)
        if (  CC_TELECOMMANDFACTORY(obj)->poolPUSDumpMemoryOffset[i]==pNULL )
            return false;
     
    if ( CC_TELECOMMANDFACTORY(obj)->poolPUSMemoryLoadAbsolute==pNULL )
        return false;

    for (unsigned int i=0; i< CC_TELECOMMANDFACTORY(obj)->sizePUSMemoryLoadAbsolute; i++)
        if (  CC_TELECOMMANDFACTORY(obj)->poolPUSMemoryLoadAbsolute[i]==pNULL )
            return false;
     
    if ( CC_TELECOMMANDFACTORY(obj)->poolPUSMemoryLoadOffset==pNULL )
        return false;

    for (unsigned int i=0; i< CC_TELECOMMANDFACTORY(obj)->sizePUSMemoryLoadOffset; i++)
        if (  CC_TELECOMMANDFACTORY(obj)->poolPUSMemoryLoadOffset[i]==pNULL )
            return false;
     
    if ( CC_TELECOMMANDFACTORY(obj)->poolTestPUSTelecommand==pNULL )
        return false;

    for (unsigned int i=0; i< CC_TELECOMMANDFACTORY(obj)->sizeTestPUSTelecommand; i++)
        if (  CC_TELECOMMANDFACTORY(obj)->poolTestPUSTelecommand[i]==pNULL )
            return false;
     

   return true;
}
///////////////////////////////////////////////////////////////////////////////
//
//                   object constructor and destructor
//
///////////////////////////////////////////////////////////////////////////////
// the following may be useful if you don't need it, just delete.
// CC_TelecommandFactory *this = CC_TELECOMMANDFACTORY(obj)
static void instance_init(Object *obj)
{
   CC_RootObject_setClassId(ID_TELECOMMANDFACTORY);

  CC_TELECOMMANDFACTORY(obj)->sizeDummyPUSTelecommand = 1;
     CC_TELECOMMANDFACTORY(obj)->poolDummyPUSTelecommand = (DC_DummyPUSTelecommand**)malloc( CC_TELECOMMANDFACTORY(obj)->sizeDummyPUSTelecommand*sizeof(DC_DummyPUSTelecommand*));
    for (unsigned int i=0; i< CC_TELECOMMANDFACTORY(obj)->sizeDummyPUSTelecommand; i++)
        CC_TELECOMMANDFACTORY(obj)->poolDummyPUSTelecommand[i] = pNULL;
      CC_TELECOMMANDFACTORY(obj)->sizeDummyTelecommand = 2;
     CC_TELECOMMANDFACTORY(obj)->poolDummyTelecommand = (DC_DummyTelecommand**)malloc( CC_TELECOMMANDFACTORY(obj)->sizeDummyTelecommand*sizeof(DC_DummyTelecommand*));
    for (unsigned int i=0; i< CC_TELECOMMANDFACTORY(obj)->sizeDummyTelecommand; i++)
        CC_TELECOMMANDFACTORY(obj)->poolDummyTelecommand[i] = pNULL;
      CC_TELECOMMANDFACTORY(obj)->sizePUSControlDataReporting = 1;
     CC_TELECOMMANDFACTORY(obj)->poolPUSControlDataReporting = (DC_PUSControlDataReporting**)malloc( CC_TELECOMMANDFACTORY(obj)->sizePUSControlDataReporting*sizeof(DC_PUSControlDataReporting*));
    for (unsigned int i=0; i< CC_TELECOMMANDFACTORY(obj)->sizePUSControlDataReporting; i++)
        CC_TELECOMMANDFACTORY(obj)->poolPUSControlDataReporting[i] = pNULL;
      CC_TELECOMMANDFACTORY(obj)->sizePUSDefineDataReporting = 1;
     CC_TELECOMMANDFACTORY(obj)->poolPUSDefineDataReporting = (DC_PUSDefineDataReporting**)malloc( CC_TELECOMMANDFACTORY(obj)->sizePUSDefineDataReporting*sizeof(DC_PUSDefineDataReporting*));
    for (unsigned int i=0; i< CC_TELECOMMANDFACTORY(obj)->sizePUSDefineDataReporting; i++)
        CC_TELECOMMANDFACTORY(obj)->poolPUSDefineDataReporting[i] = pNULL;
      CC_TELECOMMANDFACTORY(obj)->sizePUSDumpMemoryAbsolute = 1;
     CC_TELECOMMANDFACTORY(obj)->poolPUSDumpMemoryAbsolute = (DC_PUSDumpMemoryAbsolute**)malloc( CC_TELECOMMANDFACTORY(obj)->sizePUSDumpMemoryAbsolute*sizeof(DC_PUSDumpMemoryAbsolute*));
    for (unsigned int i=0; i< CC_TELECOMMANDFACTORY(obj)->sizePUSDumpMemoryAbsolute; i++)
        CC_TELECOMMANDFACTORY(obj)->poolPUSDumpMemoryAbsolute[i] = pNULL;
      CC_TELECOMMANDFACTORY(obj)->sizePUSDumpMemoryOffset = 1;
     CC_TELECOMMANDFACTORY(obj)->poolPUSDumpMemoryOffset = (DC_PUSDumpMemoryOffset**)malloc( CC_TELECOMMANDFACTORY(obj)->sizePUSDumpMemoryOffset*sizeof(DC_PUSDumpMemoryOffset*));
    for (unsigned int i=0; i< CC_TELECOMMANDFACTORY(obj)->sizePUSDumpMemoryOffset; i++)
        CC_TELECOMMANDFACTORY(obj)->poolPUSDumpMemoryOffset[i] = pNULL;
      CC_TELECOMMANDFACTORY(obj)->sizePUSMemoryLoadAbsolute = 2;
     CC_TELECOMMANDFACTORY(obj)->poolPUSMemoryLoadAbsolute = (DC_PUSMemoryLoadAbsolute**)malloc( CC_TELECOMMANDFACTORY(obj)->sizePUSMemoryLoadAbsolute*sizeof(DC_PUSMemoryLoadAbsolute*));
    for (unsigned int i=0; i< CC_TELECOMMANDFACTORY(obj)->sizePUSMemoryLoadAbsolute; i++)
        CC_TELECOMMANDFACTORY(obj)->poolPUSMemoryLoadAbsolute[i] = pNULL;
      CC_TELECOMMANDFACTORY(obj)->sizePUSMemoryLoadOffset = 1;
     CC_TELECOMMANDFACTORY(obj)->poolPUSMemoryLoadOffset = (DC_PUSMemoryLoadOffset**)malloc( CC_TELECOMMANDFACTORY(obj)->sizePUSMemoryLoadOffset*sizeof(DC_PUSMemoryLoadOffset*));
    for (unsigned int i=0; i< CC_TELECOMMANDFACTORY(obj)->sizePUSMemoryLoadOffset; i++)
        CC_TELECOMMANDFACTORY(obj)->poolPUSMemoryLoadOffset[i] = pNULL;
      CC_TELECOMMANDFACTORY(obj)->sizeTestPUSTelecommand = 3;
     CC_TELECOMMANDFACTORY(obj)->poolTestPUSTelecommand = (DC_TestPUSTelecommand**)malloc( CC_TELECOMMANDFACTORY(obj)->sizeTestPUSTelecommand*sizeof(DC_TestPUSTelecommand*));
    for (unsigned int i=0; i< CC_TELECOMMANDFACTORY(obj)->sizeTestPUSTelecommand; i++)
        CC_TELECOMMANDFACTORY(obj)->poolTestPUSTelecommand[i] = pNULL;
      

}

CC_TelecommandFactory* CC_TelecommandFactory_new(void)
{
        return (CC_TelecommandFactory*)object_new(TYPE_CC_TELECOMMANDFACTORY);

}



///////////////////////////////////////////////////////////////////////////////
//
//                   binding and type registration
//
///////////////////////////////////////////////////////////////////////////////

static void class_init(ObjectClass *oc, void *data)
{
CC_TelecommandFactoryClass *dc_p_class = CC_TELECOMMANDFACTORY_CLASS(oc);

        dc_p_class->isObjectConfigured = isObjectConfigured;

}

static const TypeInfo type_info = {
        .name = TYPE_CC_TELECOMMANDFACTORY,
        .parent = TYPE_CC_ROOTOBJECT,
        .instance_size = sizeof(CC_TelecommandFactory),
        .abstract = false,
        .class_size = sizeof(CC_TelecommandFactoryClass),
        .instance_init = instance_init,
        .class_init = class_init,

};

void CC_TelecommandFactory_register(void)
{
        type_register_static(&type_info);

}

